### PR TITLE
Prepare release version 0.0.3

### PR DESCRIPTION
**Pull request by koenrh**
Version bump so that new version (with [updated README](https://github.com/blendle/emailcorrect/pull/4)) can be published.

### CODE REVIEW

**Review by Jasperste — APPROVED** [review]

**Review by jurriaan — APPROVED** [review]

**Comment by elmarburke** [comment]
Now it is a breaking change in semver, but the change is only a update Readme, right? Maybe jump to 1.0.0 to have the full power of semver and this is no issue in the future.

**Comment by jurre** [comment]
Not a breaking change in semver AFAIK:

> Given a version number MAJOR.MINOR.PATCH, increment the:
>
> MAJOR version when you make incompatible API changes,
> MINOR version when you add functionality in a backwards-compatible manner, and
> PATCH version when you make backwards-compatible bug fixes.

But 1.0.0 seems like a good idea to me as well

**Review by danielsneijers — APPROVED** [review]

**Review by jurre — APPROVED** [review]

**Comment by elmarburke** [comment]
@jurre if you have leading zeros, they get removed and here you'll get 3=>4 which is a major. Removing the zeros is a development step to make sure you don't have to care about breaking changes and a hight major number in the beginning.

**Comment by JeanMertz** [comment]
> if you have leading zeros, they get removed and here you'll get 3=>4 which is a major.

Is this a SemVer thing? I never heard of this semantic.

**Comment by koenrh** [comment]
I'm cleaning up my 'open pull requests' tab. Can we merge this PR? Otherwise, I'd like to close it.

**Comment by danielsneijers** [comment]
yes, go for it dude

**Pull request merged**
